### ISSUE TITLE
Output model can't work, does this work for sdxl?

### ISSUE THREAD

**Issue by Damarcreative** [Faildes/Chattiori-Model-Merger#3]
I combined the SDXL checkpoint model. However, when trying to run it on the stable diffusion used, it doesn't work. When executed successfully, it produces a black image.
does it work for SDXL or SD1.5?

```
!python merge.py WS {model_path} {model_1} {model_2} --alpha 0.45 --vae {vae} --prune ----save_safetensors --output imaginix
```

![Screenshot from 2024-02-17 11-29-08](https://github.com/Faildes/Chattiori-Model-Merger/assets/106896172/aa62f0ff-17ce-42d0-b4b2-765e37a0181d)

**Comment by Faildes** [comment]
Thanks for remind it!
I updated the merger to run it with SDXL as well.

**Comment by Damarcreative** [comment]
I got an error message when saving the model,
I'm using 2xT4 29gb ram and using 28.7gb for merging,
Is this error caused by lack of RAM?

![Screenshot from 2024-03-08 15-40-48](https://github.com/Faildes/Chattiori-Model-Merger/assets/106896172/d4162905-ca81-40b6-8b6e-bb0ad86f5b15)

**Comment by Faildes** [comment]
I think the error is caused by either
1. Lack of RAM
2. Lack of space

Either way, you can avoid them by delete the source file (non-pruned file) using `--delete_source`, pruning each model first which something like below:
`!python merge.py "NoIn" {model_path} {model_1} None --vae {vae} --prune --delete_source --save_safetensors --output "TEMP_A"`
Add something similar to `!pip cache purge` would help decrease the VRAM usage.
So, the final code would be:
`!python merge.py "NoIn" {model_path} {model_1} None --vae {vae} --prune --delete_source --save_safetensors --output "Pruned_1"`
`!pip cache purge`
`!python merge.py "NoIn" {model_path} {model_2} None --vae {vae} --prune --delete_source --save_safetensors --output "Pruned_2"`
`!pip cache purge`
`!python merge.py {mode} {model_path} "Pruned_1.safetensors" "Pruned_2.safetensors" --alpha {alpha} --vae {vae} --prune --delete_source --save_safetensors --output {output}`
`!pip cache purge`

**Comment by Faildes** [comment]
One thing to mention, you can save the storage if you create path like `/kaggle/temp/` using `os.mkdir("/kaggle/temp/")` and save all models to that path.
